# Generated by Django 5.2.4 on 2025-07-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='users',
            new_name='members',
        ),
    ]
