# Generated by Django 5.1.1 on 2025-08-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0005_alter_board_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-Do', 'to-Do'), ('in-Progress', 'in-Progress'), ('review', 'review'), ('done', 'done')], default='to-Do', max_length=15),
        ),
    ]
